# Generated by Django 4.2.5 on 2023-11-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256, verbose_name="Идентификатор")),
                ("value", models.CharField(max_length=256, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Канал трафика",
                "verbose_name_plural": "Каналы трафика",
                "db_table": "traffic_channels",
                "ordering": ("-key",),
            },
        ),
        migrations.CreateModel(
            name="FunnelChannelUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048, verbose_name="URL")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("intensive3day", "Интенсив 3 дня"),
                            ("intensive2day", "Интенсив 2 дня"),
                            ("chatgpt", "ChatGPT"),
                            ("course7lesson", "Курс 7 уроков"),
                        ],
                        max_length=16,
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Url канала трафика",
                "verbose_name_plural": "Url каналов трафика",
                "db_table": "traffic_funnel_channel_url",
                "ordering": ("-url",),
            },
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048, verbose_name="Url")),
            ],
            options={
                "verbose_name": "Посадочная страница",
                "verbose_name_plural": "Посадочные страницы",
                "db_table": "traffic_landing_pages",
                "ordering": ("-url",),
            },
        ),
    ]
