# Generated by Django 4.2.5 on 2023-11-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Платный трафик"),
        ),
        migrations.AlterField(
            model_name="funnelchannelurl",
            name="group",
            field=models.CharField(
                choices=[
                    ("intensive3day", "Интенсив 3 дня"),
                    ("intensive2day", "Интенсив 2 дня"),
                    ("chatgpt", "ChatGPT. Курс 5 уроков"),
                    ("course7lesson", "Курс AI. 7 уроков"),
                    ("neirostaff", "Нейростафф"),
                    ("chatgptveb", "ChatGPT. Вебинар"),
                ],
                max_length=16,
                verbose_name="Группа",
            ),
        ),
    ]
