# Generated by Django 4.2.5 on 2023-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0002_landingpage_paid_alter_funnelchannelurl_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="key",
            field=models.CharField(
                blank=True, max_length=256, unique=True, verbose_name="Идентификатор"
            ),
        ),
    ]
