# Generated by Django 4.2.5 on 2023-10-13 07:58

import apps.sources.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Вероятность не может быть меньше 0'), django.core.validators.MaxValueValidator(1.0, message='Вероятность не может быть больше 1')], verbose_name='Вероятность выпадения')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'db_table': 'roulette_bonus_data',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, validators=[apps.sources.validators.google_sheet_name_validator], verbose_name='Название')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Google таблица',
                'verbose_name_plural': 'Google таблицы',
                'db_table': 'roulette_google_sheets',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Группа')),
                ('probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Вероятность не может быть меньше 0'), django.core.validators.MaxValueValidator(1.0, message='Вероятность не может быть больше 1')], verbose_name='Вероятность выпадения')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'roulette_group_data',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.CharField(default='3c0d52f76e5a44a4869e', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('bonus', models.ManyToManyField(to='roulette.bonus')),
                ('google_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roulette.googlesheet', verbose_name='google spreadsheet')),
            ],
            options={
                'verbose_name': 'Рулетка',
                'verbose_name_plural': 'Рулетки',
                'db_table': 'roulette_data',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='bonus',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.group', verbose_name='Группа'),
        ),
    ]
