# Generated by Django 4.2.5 on 2023-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='uuid',
            field=models.CharField(default='301894988c9c411c8225', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
