# Generated by Django 4.2.5 on 2023-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_alter_bonus_name_alter_roulette_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheet',
            name='name',
        ),
        migrations.AlterField(
            model_name='roulette',
            name='uuid',
            field=models.CharField(default='53205bc2af374371ae2c', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
