# Generated by Django 4.2.5 on 2023-10-17 06:32

import apps.roulette.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roulette", "0003_remove_googlesheet_name_alter_roulette_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roulette",
            name="uuid",
            field=models.CharField(
                default=apps.roulette.models.default_uuid_slice20,
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
